# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0010_auto_20170328_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Events')),
                ('friends', models.ManyToManyField(related_name='_accounts_friends_+', to='accounts.Accounts')),
            ],
        ),
    ]
