# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170404_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
