# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170404_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='events',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
