# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20170313_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
