# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20170313_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 3, 13)),
        ),
    ]
