# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20170313_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='private',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 3, 14)),
        ),
    ]
