# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20170314_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(),
        ),
    ]
