# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20170316_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
